### ISSUE TITLE
Custom REF for Time Windows

### ISSUE THREAD

**Issue by torressa** [Kuifje02/vrpy#10]
The correct time-window resource propagation doesn't work.

Forward time resource:
![Screenshot from 2020-04-20 20-50-44](https://user-images.githubusercontent.com/23246013/79790052-752eab00-834b-11ea-9ba4-04ad1cb22c6b.png)

I think it might be related to the backward extension, so requires resurrecting of the backward custom REF.
Code [here](https://github.com/Kuifje02/vrpy/commit/5d0ee24af8626e2b4017eec0a752f98b85e1f8f6)

**Comment by torressa** [comment]
Backward REFs definitions
![back1](https://user-images.githubusercontent.com/23246013/80236650-b250b100-865b-11ea-9726-42784a0fc6ef.png)
where
![back21](https://user-images.githubusercontent.com/23246013/80236664-bc72af80-865b-11ea-9a9c-f4b4f47971ad.png)
and
![back22](https://user-images.githubusercontent.com/23246013/80236677-c0063680-865b-11ea-96cc-658270441451.png)

**Comment by torressa** [comment]
It turns out it's quite hard to come up with a generic way to merge forward and a backward labels when custom REFs are given.
It's really hard to guarantee the correct resource consumption.
It's pretty easy per problem, I just can't see a generic fix.
![feasible](https://user-images.githubusercontent.com/23246013/80248562-72e08f80-8670-11ea-9afe-4b4993a266f8.png)
The best solution I've come up for this is to create another input for BiDirectional that takes a function that does this.

**Comment by torressa** [comment]
With the current changes `test_cspy_stops_capacity_duration` works with just `exact=False` (for some reason).
Solomon doesn't work either...

**Comment by torressa** [comment]
I've changed the notation on the functions to match the paper, just cause I was struggling to see whether they were correct or not.
@Kuifje02 give them a quick check please!

**Comment by Kuifje02** [comment]
It looks pretty good to me, except for two lines in `REF_backward`, where I am not sure :

- shouldn't it be `new_res[1]-=` ?      
https://github.com/Kuifje02/vrpy/blob/b1bf4c6e664d0ebbb5f17af15bc10259ddbaae2f/vrpy/subproblem_cspy.py#L225
- In this line, we are going arc (i,j) backwards, so the feasibilty test is for node i, right ? If so I'm ok.
https://github.com/Kuifje02/vrpy/blob/b1bf4c6e664d0ebbb5f17af15bc10259ddbaae2f/vrpy/subproblem_cspy.py#L247

**Comment by torressa** [comment]
Cool thanks!!

>     * In this line, we are going along arc (i,j) backwards, so the feasibilty test is for node i, right ? 

Yep!

> If so I'm ok (in the paper, the author refers to node j, hence the doubt).

That's what I thought! It's written in the same way for the forward feasibility check.

**Comment by torressa** [comment]
I think this might work now. 
Used the joining as specified in the paper too.
Running all the Solomon tests to be sure.
