### ISSUE TITLE
num_vehicles ignored

### ISSUE THREAD

**Issue by piaulous** [Kuifje02/vrpy#111]
Hello again, 

I'm coming along with another issue regarding the option num_vehicles. I'm trying to solve a CVRP for a quite huge street network (matrix dimension of 196). I'd like to have a fleet of max. 5 vehicles, but the solution gives me 35 routes in total. Do you have any suggestions? Are there any limitations on the Clark & Wright heuristic?

[Notebook](https://nbviewer.jupyter.org/github/piaulous/vrpy_testing/blob/main/vrpy_testing.ipynb)

**Comment by piaulous** [comment]
Looks like the implementation of Clarke & Wright does not have an argument  `num_vehicles`. How could I add this functionality to my model?

**Comment by Kuifje02** [comment]
Hi @piaulous, Clarke & Wright is a constructive heuristic, therefore the `num_vehicles` does not apply.

**Comment by piaulous** [comment]
Does your answer mean, that implementing a limited fleet for Clarke & Wright is just not possible or that an implementation like that won't work for vrpy?

**Comment by Kuifje02** [comment]
Yes indeed, implementing a limited fleet for Clarke & Wright is just not possible, as routes are built sequentially and are an output of the algorithm.
