### ISSUE TITLE
Solomon test fails with n=16 nodes

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#12]
https://github.com/Kuifje02/vrpy/blob/134c361d2a83f0a303b22d70552ffdc19530e5c3/tests/test_cvrptw_solomon_range.py#L11

Lp and cspy version yield different results.

**Comment by torressa** [comment]
Works for me for n =16 What version of cspy have you got?
It fails for me for n = 28 and 29 though. No idea why though...

**Comment by Kuifje02** [comment]
Yes maybe I am not using the latest cspy version. I will check it out.

**Comment by Kuifje02** [comment]
Ok it turns out the tests were failing because of the stopping criteria (stop if no improvement after 50 iterations). I raised it to 100 and tests all succeed !
