### ISSUE TITLE
Compare with gurobi

### ISSUE THREAD

**Issue by rlacjfjin** [Kuifje02/vrpy#129]
Hi,
If I select gurobi solver with solver parameter, is it better than using gurobi solver directly?

Thanks

**Comment by romain-montagne** [comment]
What do you mean "using gurobi solver directly" ?

**Comment by rlacjfjin** [comment]
I mean use gurobi solve MIP model of vrp variants with default settings.
I want to know whether vrpy can accerate gurobi or better than gurobi. 
I remember  you compare with ortools on some benchmark dataset and better than ortools, then how gap between vrpy and gurobi solver? Of course, one is open source and another is commercial, but I want to know how good vrpy is.
Thanks

**Comment by romain-montagne** [comment]
If you use use the option `prob.solve(cspy=False)`, vrpy will solve the MIP model, which you can do with gurobi. You will see that as the size of the problem grows, the computation times grow exponentially. When using `cpsy=True`, a decomposed formulation is solved, which in theory should leed to quicker computation times. We have noticed that it is indeed the case. Feel free to play around with these options and see for your self, and get back to us if you notice anything fishy.
