### ISSUE TITLE
Implement Clark & Wright 's savings algorithm as initial solution

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#13]
Having a good initial feasible solution is always a good start. [Clark & Wright's saving algorithm](http://web.mit.edu/urban_or_book/www/book/chapter6/6.4.12.html) is a good option (good empirical results and easy to implement).

It can be adapted for time windows as well.

**Comment by torressa** [comment]
Nice!
Just had a quick google and I can't find a good python implementation

**Comment by Kuifje02** [comment]
Yes I think we'll have to do it, but it shouldn't be too hard !

**Comment by torressa** [comment]
Found this though https://github.com/yorak/VeRyPy
Haha so much stuff!!
