### ISSUE TITLE
heuristics for ESPPRC to get reduced networks

### ISSUE THREAD

**Issue by xkuan** [Kuifje02/vrpy#139]
Hello,
First of all, thank you for your great convenience in solving vrp！

I have 2 questions if you don't mind (about heuristics for ESPPRC to get reduced networks):

1. Is there any literature on this method `BestPaths`?
2. Could you please recommend some other literature on heuristics or hyperheuristics?

**Comment by romain-montagne** [comment]
Thanks for your feedback!

To my knowledge there is no specific literature for BestPaths, but I would not be surprised if it were mentioned in different articles. I would recommend [this book](https://link.springer.com/book/10.1007/b135457): the bible of column generation.

Note also that the [cspy](https://github.com/torressa/cspy) module (on which vrpy depends) has heuristics for the SPPRC.
