### ISSUE TITLE
max duration constraints not met when time windows are active (cspy)

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#17]
The following (new) test in test_toy.py fails : 

```
def test_all(self):
        prob = VehicleRoutingProblem(
            self.G, num_stops=3, time_windows=True, duration=63, load_capacity=10
        )
        prob.solve(cspy=False)
        lp_best = prob.best_value
        prob.solve(cspy=True)
        cspy_best = prob.best_value
        assert int(lp_best) == int(cspy_best)
```
The reason is that cspy generates route _Source-4-5-Sink_ which violates the max duration constraint (it has total duration 65). We had not tested duration and time windows constraints simultaneously ^^ 

There is probably something wrong in the REF, I cannot figure out for the moment. Needs some investigation !

**Comment by torressa** [comment]
Passing!
