### ISSUE TITLE
Is it possible to add a time limit for the cspy subproblem ?

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#19]
Right now, the paramater `time_limit` has no effect when solving the subproblem with cspy :

https://github.com/Kuifje02/vrpy/blob/aa2623fad989a8c99d1f09e50c4e29a5e41ffb8c/vrpy/subproblem_cspy.py#L58-L68

I am not sure if it is possible to interrupt `alg.run()` if the `time_limit` is exceeded 
https://github.com/Kuifje02/vrpy/blob/aa2623fad989a8c99d1f09e50c4e29a5e41ffb8c/vrpy/subproblem_cspy.py#L101

This would be handy for testing data sets with a given time limit, but also for a user who wants the best solution found within the time limit. With the lp version, this is done by giving the time limit as an input to the solver.

**Comment by torressa** [comment]
Not currently, but I can definitely give it a go!

**Comment by torressa** [comment]
Moved to cspy
