### ISSUE TITLE
Diving heuristic checking and testing

### ISSUE THREAD

**Issue by torressa** [Kuifje02/vrpy#21]
I've implemented the diving heuristic (I think). 
https://github.com/Kuifje02/vrpy/blob/aaf2b51f799a54d5cb24735c623b4432138848f8/vrpy/master_solve_pulp.py#L37-L78
Seems to mostly work for the benchmarks instances: fails for some cases, but is really fast. However, I'm not entirely sure whether it should be run just at the last iteration as it now (when the optimal solution to the LP relaxation has been found) 
https://github.com/Kuifje02/vrpy/blob/aaf2b51f799a54d5cb24735c623b4432138848f8/vrpy/main.py#L189-L191
OR all the way through the column generation procedure (?). The paper just makes me more confused every time I read it :laughing: 

Anyway, if I've implemented correctly, might be worth comparing between the solution given by the integer master, both in objective value and solution time.

**Comment by Kuifje02** [comment]
To be honest the paper made me confused too! 

Here is how I understand things:
- If you generate columns and then solve as a MIP (as we currently do), you are performing _price-and-branch_.
- If you generate columns, then branch, and generate columns again (untill the linear formulation yields an integer solution), you are performing _branch-and-price._ 

When performing _branch-and-price,_ at each node of the tree, you want a feasible solution (an upper bound if you are minimizing). To get such an upper bound, you can solve the problem as a MIP, or, you can use a _Restricted Master Heuristic_. Among the different heuristics out there, there are the _diving techniques,_ which only explore part of the MIP tree (which differs from the branch-and-price tree). 

So the way I understand it is, if you use a diving heuristic after having generated all your columns, you are performing a heuristic version of the price-and-branch. Best case scenario, you get the same solution as the MIP. If bad luck, you get an upper bound, greater than the one obained with the MIP.  So I think the diving heuristic at the end, as it is now, is helpful if the resulting MIP is too hard to solve. But if my understanding is correct (which very well may not be!), it cannot yield a better solution than resolving as a MIP once there are no more columns with negative reduced cost.

**Comment by torressa** [comment]
Cool, at least one of us understands what's going on. I've got to go back to it again.

> So I think the diving heuristic at the end, as it is now, is helpful if the resulting MIP is too hard to solve.

The problem is then that we can't tell a priori whether the last MIP is going to be hard to solve or not. Also, sometimes the solution to the LP relaxation is already integer (in which case diving does nothing), so, I think, there's no need to solve the last MIP.

> But if my understanding is correct (which very well may not be!), it cannot yield a better solution than resolving as a MIP once there are no more columns with negative reduced cost.

That's right cause diving (as it is now) only fixes non-integer variables to 1.

**Comment by torressa** [comment]
Pretty sure it's wrong. I'll correct soon.

**Comment by torressa** [comment]
I've tested the algorithm on another problem and does improve the UB with respect to the one obtained with the MIP! 
However, in vrpy there are a few big changes for it to work. Because a new instance of `MasterProblem` is created in every iteration; there's no clean way of passing the constraints that the diving heuristic fixes (and the other algorithm specific stuff like the new attribute `MasterProblem._tabu_list`).

I'll see if I come up with an easy solution, but I think its cleaner (and probs slightly faster too) to update the formulation instead of reformulating it every time (maybe using the `pulp.LpProblem.extend` method). First issue for the intern maybe..

**Comment by torressa** [comment]
Updated version should eventually work (whenever the model is reworked as described above)
Previously version was fixing variables to 0 (which is not what we want...)

**Comment by torressa** [comment]
Actually wasn't quite right. @Halvaros is working on it.
We've found the only benchmark where it is beneficial is on the Augerat instances.. We'll see...

**Comment by torressa** [comment]
This works now. Just need to find some more challenging cases to see if the integrality gap is improved. See #42

**Comment by torressa** [comment]
@Halvaros
Some of the "challenging but still solvable" Augerat instances to test diving 
- P-n19-k2.vrp
- P-n20-k2.vrp
- P-n21-k2.vrp
- P-n22-k2.vrp
- A-n33-k5.vrp
- A-n43-k6.vrp
- B-n43-k6.vrp
- B-n41-k6.vrp

Just ran some tests on some of the above. 
Not good news: 
Tried diving with `max_depth=3` (Diving with LDS) and `max_depth=bignumber` (Diving for feasibility) (note the changes of the parameter in the dev version) and they are both slower and worse than the solution from the MIP.
Diving for feasibility results for P-n19-k2.vrp below

![diving_for_feasibility](https://user-images.githubusercontent.com/23246013/88273017-dc0c8900-ccd9-11ea-9386-dc42d03acc4d.png)

Doubting the algorithm again, needs revisiting.

**Comment by torressa** [comment]
New stuff in branch `patch21`

**Comment by torressa** [comment]
I've taken the diving heuristic out of master_solve_pulp in the spirit of having a specific file to implement other primal heuristics (not pricing). I think the diving heuristic is mostly correct, however, it turns out it's only good when the lower bound is tight. Alternatively see #60

Here are some more results. 
Instances where it doesn't harm/improves are P-n16-k8.vrp and P-n22-k2. See table below.
(Just realised you can copy and paste from excel haha)

Instance | Dived | Greedy | Runtime | # of iterations | Integrality gap | Optimality gap | Optimal
-- | -- | -- | -- | -- | -- | -- | --
A-n32-k5.vrp | True | True | 17325 | 155 | 183.80 | 175.13 | False
A-n32-k5.vrp | False | True | 20824 | 158 | 7.08 | 3.70 | False
A-n33-k5.vrp | True | True | 11314 | 132 | 34.87 | 33.89 | False
A-n33-k5.vrp | False | True | 10370 | 101 | 2.04 | 1.21 | False
P-n16-k8.vrp | True | True | 4 | 10 | 2.04 | 0.00 | True
P-n16-k8.vrp | False | True | 2 | 6 | 2.04 | 0.00 | True
P-n16-k8.vrp | True | True | 3 | 7 | 2.04 | 0.00 | True
P-n16-k8.vrp | False | True | 2 | 5 | 2.04 | 0.00 | True
P-n19-k2.vrp | True | True | 458 | 113 | 39.02 | 33.96 | False
P-n19-k2.vrp | False | True | 504 | 101 | 6.46 | 3.30 | False
P-n19-k2.vrp | True | True | 571 | 121 | 31.19 | 26.42 | False
P-n20-k2.vrp | True | True | 1289 | 168 | 45.77 | 43.52 | False
P-n20-k2.vrp | False | True | 1136 | 132 | 4.53 | 2.78 | False
P-n21-k2.vrp | True | True | 1976 | 178 | 15.09 | 15.64 | False
P-n21-k2.vrp | False | True | 1344 | 159 | 3.24 | 3.32 | False
P-n22-k2.vrp | True | True | 1898 | 161 | 0.00 | 0.00 | True
P-n22-k2.vrp | False | True | 1709 | 157 | 6.13 | 7.41 | False
