### ISSUE TITLE
Load_capacity constraint breaches

### ISSUE THREAD

**Issue by egh312** [Kuifje02/vrpy#22]
Think the library is a great idea!

Have come across a minor issue with load_capacity breaches.

![image](https://user-images.githubusercontent.com/66272009/83440010-107f6980-a43c-11ea-85dc-f6d4ee7edb61.png)

**Comment by Kuifje02** [comment]
Thank you for your feedback. I assume $A$ is the distance/cost matrix ? Can you just provide the demands for each node so that I can replicate the error ?

**Comment by Kuifje02** [comment]
When I run the following code, it seems ok :

```
from networkx import from_numpy_matrix, set_node_attributes, relabel_nodes, DiGraph
from numpy import matrix
from vrpy import VehicleRoutingProblem

DISTANCES = [
    [0, 407, 13916, 189591, 190473, 0],
    [0, 0, 13805, 189480, 190361, 407],
    [0, 0, 13805, 189480, 190361, 407],
    [0, 189098, 176331, 0, 1943, 189328],
    [0, 189515, 176749, 1943, 0, 189746],
    [0, 0, 0, 0, 0, 0],
]
DEMANDS = {1: 1, 2: 2, 3: 1, 4: 2}

# Transform distance matrix to DiGraph
A = matrix(DISTANCES, dtype=[("cost", int)])
G = from_numpy_matrix(A, create_using=DiGraph())

# Set demands
set_node_attributes(G, values=DEMANDS, name="demand")

# Relabel depot
G = relabel_nodes(G, {0: "Source", 5: "Sink"})


if __name__ == "__main__":

    print(A)
    prob = VehicleRoutingProblem(G, load_capacity=2)
    prob.solve(pricing_strategy="PrunePaths")
    print(prob.best_value)
    print(prob.best_routes)
    print(prob.best_routes_load)
```
This is the output :

```
[[(     0,) (   407,) ( 13916,) (189591,) (190473,) (     0,)]
 [(     0,) (     0,) ( 13805,) (189480,) (190361,) (   407,)]
 [(     0,) (     0,) ( 13805,) (189480,) (190361,) (   407,)]
 [(     0,) (189098,) (176331,) (     0,) (  1943,) (189328,)]
 [(     0,) (189515,) (176749,) (  1943,) (     0,) (189746,)]
 [(     0,) (     0,) (     0,) (     0,) (     0,) (     0,)]]
INFO:vrpy.main:new upper bound : max num stops = 4
INFO:vrpy.main:Initial solution found with value 395899
INFO:vrpy.main:iteration 0, 395899.0
INFO:vrpy.main:iteration 1, 395899.0
INFO:vrpy.master_solve_pulp:total cost = 395899.0
395899
{1: ['Source', 1, 2, 'Sink'], 2: ['Source', 3, 4, 'Sink']}
{1: 3, 2: 3}
```

@egh312 Please let me know how to change the data (the demands) to have the exact same problem as you.

**Comment by egh312** [comment]
Apologies, I see my mistake now - i'd given the Sink node a demand

Seems to rightly fail when i increase any demand node above 1

![image](https://user-images.githubusercontent.com/66272009/83500676-ff277300-a4b6-11ea-938e-17af3a1d7025.png)

**Comment by Kuifje02** [comment]
This being said, you have still pointed out something interesting, it might be a good idea to raise an error if the Sink's demand is not 0. 
And If you need really a demand at the sink, you can split the `Sink` into two vertices `dummy_node`, and `Sink` with a cost=0 between the two, and the demand at the `dummy_node.`
