### ISSUE TITLE
How to make sure time limit is not exceeded

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#23]
If the colgen procedure searches for variables until the time limit is passed, there is no time left for the final MIP.

https://github.com/Kuifje02/vrpy/commit/f0d5b7b4a0232d363b969cbe7c98ab584475fafb#r39585343

Different possibilities:

- take a few seconds from the input time limit to solve the last MIP
- warn the user that the total time may exceed the input time limit
- ...

**Comment by torressa** [comment]
Another option could be: solve the last MIP disregarding the time limit. 
Can't take more than a few seconds, if that..

**Comment by Kuifje02** [comment]
> Another option could be: solve the last MIP disregarding the time limit.
> Can't take more than a few seconds, if that..

In this spirit, we could redefine `get_remaining_time()` as  max(remaining time,5) ? 

This way, there is always some time left (5 seconds) for the last MIP and all the work done before is not lost, and it is guaranteed that if the real time limit passed, it is "only" 5 extra seconds. Maybe 5 is not the right number.
