### ISSUE TITLE
Question : Is there a simple starter example of Periodic VRP with a month of planning period ?

### ISSUE THREAD

**Issue by sumi1234** [Kuifje02/vrpy#28]
In the documentation, I noticed that just setting the frequency of visits for each node is given as an option. How do I set the duration ( planning period ) and define periodicity in a better way ?

Also - how would I get the routes for each day in the planning period from the solved problem.

I have a central depot where nodes ( customers ) are to be visited a certain number of times every month. 

```
G.nodes[1]["frequency"] = 2
prob.periodic = True

```

Apologies if the question is very basic. I am new to vehicle routing problems. Any help would be appreciated  !

**Comment by Kuifje02** [comment]
> In the documentation, I noticed that just setting the frequency of visits for each node is given as an option. How do I set the duration ( planning period ) and define periodicity in a better way ?

Right now, there is no other way to define periodicity: only frequencies are considered. In future versions, hopefully we will be able to also take into account possible combinations of visit days. For example, if frequency is 2 over a 3 day period, a possible combination could be days 1 and 3, or days 1 and 2.  This is how the Periodic CVRP is formally defined. This is part of the TO DO list :)

> Also - how would I get the routes for each day in the planning period from the solved problem.

Currently this is also beyond the scope of vrpy. If you are familiar with linear programming you could schedule the routes each day as follows. Define a binary variable x(r,t) that takes value 1 if and only if route r is scheduled on day t, and use the following constraints:

1) Each route must be scheduled: Sum_{t} x(r,t) = 1 for each road r
2) A customer cannot be visited more than once per day: Sum_{r, v in r} x(r,t) <= 1 for each day t, for each customer v

Hopefully we can integrate soemthing like this soon directly in vrpy.


> Apologies if the question is very basic. I am new to vehicle routing problems. Any help would be appreciated !

This is actually a good question ;)

**Comment by Kuifje02** [comment]
@sumi1234 
if you git clone the  current master branch, you can access a schedule as follows:
```
prob.periodic = YOUR_TIME_SPAN
prob.solve()
prob.schedule
```
I will update the docs soon with a starter example. But in the mean time this should work.

**Comment by sumi1234** [comment]
Thank you so much !! I will try this out. I think this would be a great starting point. 

Appreciate the quick support :)

**Comment by sumi1234** [comment]
Thanks again ! I was able to run it on dummy data using a 10 day planning period and I have started using it for my problem.

Code snippet is provided for future reference below [ Hope I have understood the changes correctly ]

```
DISTANCES = [
    [0,548,776,696,582,274,502,194,308,194,536,502,388,354,468,776,662,0], # from Source
    [0,0,684,308,194,502,730,354,696,742,1084,594,480,674,1016,868,1210,548],
    [0,684,0,992,878,502,274,810,468,742,400,1278,1164,1130,788,1552,754,776],
    [0,308,992,0,114,650,878,502,844,890,1232,514,628,822,1164,560,1358,696],
    [0,194,878,114,0,536,764,388,730,776,1118,400,514,708,1050,674,1244,582],
    [0,502,502,650,536,0,228,308,194,240,582,776,662,628,514,1050,708,274],
    [0,730,274,878,764,228,0,536,194,468,354,1004,890,856,514,1278,480,502],
    [0,354,810,502,388,308,536,0,342,388,730,468,354,320,662,742,856,194],
    [0,696,468,844,730,194,194,342,0,274,388,810,696,662,320,1084,514,308],
    [0,742,742,890,776,240,468,388,274,0,342,536,422,388,274,810,468,194],
    [0,1084,400,1232,1118,582,354,730,388,342,0,878,764,730,388,1152,354,536],
    [0,594,1278,514,400,776,1004,468,810,536,878,0,114,308,650,274,844,502],
    [0,480,1164,628,514,662,890,354,696,422,764,114,0,194,536,388,730,388],
    [0,674,1130,822,708,628,856,320,662,388,730,308,194,0,342,422,536,354],
    [0,1016,788,1164,1050,514,514,662,320,274,388,650,536,342,0,764,194,468],
    [0,868,1552,560,674,1050,1278,742,1084,810,1152,274,388,422,764,0,798,776],
    [0,1210,754,1358,1244,708,480,856,514,468,354,844,730,536,194,798,0,662],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], # from Sink
    ]
    
# Demands (key: node, value: amount)
DEMAND = {1: 1, 2: 1, 3: 2, 4: 4, 5: 2, 6: 4, 7: 8, 8: 8, 9: 1, 10: 2, 11: 1, 12: 2, 13: 4, 14: 4, 15: 8, 16: 8}

# Frequencies (key: node, value: frequency in planning period)
FREQ = {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 4, 7: 5, 8: 3, 9: 1, 10: 8, 11: 4, 12: 2, 13: 2, 14: 2, 15: 2, 16: 2}

# The matrix is transformed into a DiGraph
A = matrix(DISTANCES, dtype=[("cost", int)])
G = from_numpy_matrix(A, create_using=nx.DiGraph())

# The demands are stored as node attributes
set_node_attributes(G, values=DEMAND, name="demand")

##Setting the frequency for each node
set_node_attributes(G, values=FREQ, name="frequency") 

# The depot is relabeled as Source and Sink
G = relabel_nodes(G, {0: "Source", 17: "Sink"})

prob = VehicleRoutingProblem(G, load_capacity=15)

# Setting planning horizon to 10 days 
prob.periodic = 10
    
prob.solve()
    
#Note : Some days might have zero routes
for route_num, route_keys in sorted(prob.schedule.items()):
    print("\nRoute for Day " + str(route_num), " : ")
    i = 1
    for k in route_keys:
        print("\tRoute ",i," : ",prob.best_routes[k])
        i=i+1
   
print("Total Cost of set of optimum Route : ", prob.best_value)
```

**Comment by Kuifje02** [comment]
Note that currently, `prob.schedule`  returns a feasible schedule. It would be easy to optimize some criteria to have a balanced schedule. 
If you have a suggestion or a specific criteria (for example and avoid days with zero routes) , it would probably be quite easy to implement.

**Comment by sumi1234** [comment]
Thank you ! Avoiding days with zero routes or having a more balanced schedule would be a great feature. I have seen that it is usually implemented through a penalty for partially loaded/unused vehicles.

Following criteria would be great to have - 
- Balanced routes across days ( e.g. by adding a user-specified penalty variable depending on utilization of vehicles OR adding a penalty basis difference between min and max number of routes in a schedule)
- Define spacing between visits to further filter down feasible routes ( e.g. weekly, every 2 weeks ). 

Unrelated question. Is there any way to save created schedules/data every hour or so ( a sort of checkpoint ). It would be extremely useful especially while running on bigger data.

**Comment by Kuifje02** [comment]
> Following criteria would be great to have -
> 
> * Balanced routes across days ( e.g. by adding a user-specified penalty variable depending on utilization of vehicles OR adding a penalty basis difference between min and max number of routes in a schedule)
> * Define spacing between visits to further filter down feasible routes ( e.g. weekly, every 2 weeks ).

Great suggestions, thanks! Will be implemented soon ;)




> Unrelated question. Is there any way to save created schedules/data every hour or so ( a sort of checkpoint ). It would be extremely useful especially while running on bigger data.

What do you mean every hour ? You need to run the algorithm every hour and save the schedule ?

**Comment by sumi1234** [comment]
> Great suggestions, thanks! Will be implemented soon ;)
Awesome !!!

> What do you mean every hour ? You need to run the algorithm every hour and save the schedule ?
On large datasets, the heuristic algorithm has a run-time > 1 hour if I don't set a time-limit. 
I am curious to have the intermediate results saved every hour at a particular location ( maybe .pkl files ). This would help me analyze what value I should give to the time_limit parameter when I run it again and also serves as a pseudo early-stopping criteria.

Currently I set exact=False on large datasets and run the solution on different values of time_limit to determine this.

**Comment by Kuifje02** [comment]
aa ok I see. Hmm currently this is hardly possible, but I will think about it. 



> Currently I set exact=False on large datasets and run the solution on different values of time_limit to determine this

Also, it is worth trying with `exact=True`, sometimes, depending on the data sets, we have noticed the exact version is better. We are working on it as well.

**Comment by Kuifje02** [comment]
If you git clone the current master branch, a balanced schedule is computed (the difference between the maximum number of routes per day and minimum routes per day is minimized). However spacing the visits is a bit more tricky.

**Comment by sumi1234** [comment]
Thanks for making the changes. I will test them out over the weekend ! Will share thoughts after the same.

**Comment by sumi1234** [comment]
I think the changes do help in making the routes more balanced. Adding a fixed cost per vehicle ( fixed_cost parameter) with the latest changes helped me reach a workable solution for my problem.

How is the fixed cost added to the total cost value for periodic VRP ? It seems like it is being added to each day of the planning period/routes

**Comment by Kuifje02** [comment]
Yes exactly, the fixed cost is added on a per route basis, so it is charged for every route, every day of the planning period. It could be the driver's salary for example.
