### ISSUE TITLE
exact = False, which metaheuristic?

### ISSUE THREAD

**Issue by egh312** [Kuifje02/vrpy#29]
Hello again!

Is it possible to know which metaheuristic is called from cspy when exact = False?

I can see there is a _solver in the vars of the VehicleRoutingProblem but unsure what this relates to
![image](https://user-images.githubusercontent.com/66272009/84603275-079f8680-ae85-11ea-99b8-4f958342914a.png)

Best
Ed

**Comment by torressa** [comment]
Morning Ed! It's a [greedy eliminiation](https://cspy.readthedocs.io/en/latest/api/cspy.GreedyElim.html) algorithm (removes edges until resource feasible path is found). However, it's not that great, and is sometimes slower than the exact algorithm,.

**Comment by Kuifje02** [comment]
To complete @torressa answer, there is indeed a `_solver`  argument. Iteratively, a "master problem" and a "sub problem" are solved. The master problem is solved with the `_solver` (CBC from Coin OR), and the sub problem is solved with a metaheuristic (if `cpsy=False`), namely the greedy elimination mentioned above.

**Comment by egh312** [comment]
Perfect, thank you!
