### ISSUE TITLE
How to handle cspy.res_cost object if it has variable length ?

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#3]
When considering the following constraints :

- maximum number of stops

- load constraints

- duration constraints

resources extension functions are additive, so it is not necessary to define a custom REF.

But when considering time windows, a custom REF is necessary with the cspy.REF_custom method :

![image](https://user-images.githubusercontent.com/19840033/78359006-783c4400-75b4-11ea-8b93-a41fac48d496.png)

How can we handle the fact that the cumulative_res object has a variable length, as it depends on which constraints are activated (load, duration, etc.) ? 

For example, we know that the monotone resource is alway first  (`new_res[0}+=1`), but not sure how to handle the other ones.

**Comment by torressa** [comment]
@Kuifje02 Just seen this. I'll have a look through the new stuff and see

**Comment by torressa** [comment]
I think I fixed it? Couldn't come up with an actual solution.
Was mostly trying to get the resource functions working
Please check the time windows resources are correct.

**Comment by Kuifje02** [comment]
I thought of another solution. Would it work if we always worked with all the resources (monotone,stops, capacity, time, time_windows, ...) and changed res_max according to the constraints that are activated ?

An obvious down side is that if you only have one constraint, for example, capacity, you have to handle all the other "dummy" resources in the algorithm. I assume this affects the computational complexity of the bidirectional algorithm (exponentially ?) ?

**Comment by torressa** [comment]
Yeh that's a much neater solution.
The number of resources should not really affect the algorithms performance.

**Comment by Kuifje02** [comment]
Partially implemented. Partially because two tests fail and I cannot figure out why for the moment. Still looking. For some reason the maximum number of stops resource fails.

**Comment by torressa** [comment]
It turned out pretty neat! 
Fixed on error, got a new one. It seems pretty tricky to get the REFs right, not easy to debug either...

**Comment by torressa** [comment]
Not sure, seems to work without the REFs.
The total resource consumption is not correct. So I think it might be a problem with cspy not dealing with custom REFs very well.

**Comment by torressa** [comment]
New commit in cspy fixes all errors except time windows.
I'll have another look into it tomorrow.

**Comment by torressa** [comment]
Works with the the version in cspy-master!!

**Comment by Kuifje02** [comment]
Nice I'll take a look !
