### ISSUE TITLE
num_vehicles 

### ISSUE THREAD

**Issue by egh312** [Kuifje02/vrpy#31]
Hello!

I'm not convinced the num_vehicles parameter is working as expected.
Running a network with 95 nodes and 8 vehicles.
Total demand is 95 (1 per node), load_capacity is 13 (13*8 =104 so some slack)

Solver doesn't appear to restrict to the 8 vehicles and repeats nodes:
![image](https://user-images.githubusercontent.com/66272009/84604484-4554dd00-ae8e-11ea-8dbe-9a139b69733f.png)

I have attached the graph pikle file too, if needed for debug:
[EH_graph.txt](https://github.com/Kuifje02/vrpy/files/4777242/EH_graph.txt)

Best.
Ed

**Comment by Kuifje02** [comment]
Thanks for you feedback.

This is a problem indeed. The EH_graph.txt is not readable, could you try another format ?

I am pretty sure this is because the graph is starting to be big.. The solver is violating the "num vehicles" constraint at the expense of a high penalty (~120000000000) We'll see how we can try and make this work.

**Comment by egh312** [comment]
Ok - that makes sense.

For the file i think if you were to save the EH_graph file and use "nx.read_gpickle" to read the path it should work
https://networkx.github.io/documentation/stable/reference/readwrite/gpickle.html

I've attached a zipped YAML file if not
[EH_graph2.zip](https://github.com/Kuifje02/vrpy/files/4779352/EH_graph2.zip)

Best. 
Ed

**Comment by Kuifje02** [comment]
Nice, I didn't know this `read_gpickle` existed, very handy !

So indeed, this is what is happening: the initial solution that is computed is not feasible as it is using more than 8 vehicles. As the algorithm converges, it should 1) improve the objective function 2) repair this infeasibility, but right now it is too slow and fails to repair with the given time limit. 

This is on our top priority items to improve ! But it is not really a bug, just a lack of efficiency. It would have been easier to fix if it were a bug!

**Comment by Kuifje02** [comment]
This data set is interesting. After playing around with it, I observed that from one heuristic to another, the solution is quite different. In particular, the Clarke & Wright heuristic used by vrpy to find an initial solution performs very poorly compared to other simple heuristics. 

How was this data generated (the costs) ?

**Comment by egh312** [comment]
Costs relate to actual distances/durations derived from the Open Source Routing Machine (OSRM).
http://project-osrm.org/docs/v5.22.0/api/#general-options

I'm currently doing my Masters thesis on vehicle routing within the context of a small service company - comparing what they do today with an analytically/programmatically driven routing. Nodes are customer locations and costs are the distances/durations between them as determined by OSRM

**Comment by Kuifje02** [comment]
If you git clone the current master branch and run the algorithm with the above data, a feasible initial solution is computed (8 vehicles). This feature will be in the next release, but in the mean time, the master branch works. Please let me know everything works fine so I can close the issue. 
PS: good luck on the masters thesis, and don't hesitate using vrpy and asking for relevant features that could help.

**Comment by egh312** [comment]
Thank you!
