### ISSUE TITLE
Formulate master pulp by columns

### ISSUE THREAD

**Issue by torressa** [Kuifje02/vrpy#32]
As mentioned [here](https://github.com/Kuifje02/vrpy/issues/21#issuecomment-638385344), for the diving heuristic to work, for some speed up, it would be good to rework `master_solve_pulp.py` such that it doesn't have to be reformulated in every iteration of the column generation procedure.

For a column generation friendly way of updating the constraints, one can formulate the problem by columns (seen an [example](https://github.com/coin-or/pulp/blob/master/examples/CGcolumnwise.py)). 

The idea is to 
1. create empty constraints using [`pulp.LpConstraintVar`](https://github.com/coin-or/pulp/blob/f804406eed817af993c403d436401b4ed4ffc2b9/pulp/pulp.py#L1078), with only the sign (<=, >=) and RHS specified. 
2. Then place variables [`pulp.LpVariable`](https://coin-or.github.io/pulp/technical/pulp.html#pulp.LpVariable) in already existing constraints with the appropriate coefficient, using the `e` parameter. Here, one can use pulp operations like `pulp.lpSum` to add variables to multiple constraints at once (this can be seen in the [example](https://github.com/coin-or/pulp/blob/f804406eed817af993c403d436401b4ed4ffc2b9/examples/CGcolumnwise.py#L84-L85))

To update the constraints throughout the column generation procedure, the constraints has have to preserved. For example as a dictionary in an attribute.

## Constraints Converted
- [x] Set Covering
- [ ] Vehicle bound

## Variables Converted
- [ ] route selecting (y)
    - [x] Simplest case
    - [ ] With vehicle bound
- [ ] Drop
- [ ] Artificial

**Comment by Kuifje02** [comment]
Excellent idea ! 

Another very simple example with explanations can be found [here](https://projects.coin-or.org/PuLP/browser/wiki/ColumnGeneration2.wiki).

**Comment by torressa** [comment]
Just opened a new branch [`patch32`](https://github.com/Kuifje02/vrpy/tree/patch32) with some initial work. See check list above for remaining conversions

**Comment by torressa** [comment]
On dev branch. Closed by #39

**Comment by torressa** [comment]
@Kuifje02 @Halvaros
Just ran the new version on the Solomon instance and comparing with the old (OLD) comp results from https://github.com/Kuifje02/vrpy/issues/8#issuecomment-612176272.
We get some pretty amazing speed up! Average of over 10,000% faster and scales a lot better!
![speed_up](https://user-images.githubusercontent.com/23246013/85753777-d5a3e500-b70c-11ea-94e5-e5310aa45cd7.png)
Needs more testing but definitely faster

**Comment by Kuifje02** [comment]
Thanks guys, great work!
