### ISSUE TITLE
Error : Float Object not subscriptable

### ISSUE THREAD

**Issue by sumi1234** [Kuifje02/vrpy#34]
I am getting this error intermittently while solving for a PVRP with a planning period of 24 days and a constraint on duration. It happens for subsets of my data and I was hoping for some direction to understand why this is happening. The error does not happen when I just use the Cost Matrix.

```
 45     prob.solve(time_limit = time_limit)

~\Desktop\Supply_Chain_Tool_Streamlined\code_w_balanced_schedules\vrpy\main.py in solve(self, initial_routes, preassignments, pricing_strategy, cspy, exact, time_limit, solver, dive, greedy)
    178 
    179         # Initialization
--> 180         self._initialize()
    181 
    182         # Column generation

~\Desktop\Supply_Chain_Tool_Streamlined\code_w_balanced_schedules\vrpy\main.py in _initialize(self)
    279             self._get_initial_solution()
    280         # Initial routes are converted to digraphs
--> 281         self._convert_initial_routes_to_digraphs()
    282         # Initialize parameters for stopping criteria
    283         self._more_routes = True

~\Desktop\Supply_Chain_Tool_Streamlined\code_w_balanced_schedules\vrpy\main.py in _convert_initial_routes_to_digraphs(self)
    514             edges = list(zip(r[:-1], r[1:]))
    515             for (i, j) in edges:
--> 516                 edge_cost = self.G.edges[i, j]["cost"][0]
    517                 G.add_edge(i, j, cost=edge_cost)
    518                 total_cost += edge_cost

TypeError: 'float' object is not subscriptable
```

For reference, the code used for setting up the problem is below : [ I am using a DISTANCE matrix similar to the OR tools example, and incorporating time by assuming an AVERAGE_SPEED in km/hour. Duration constraint is set as 10 hours per day of the planning period ]

    A = matrix(DISTANCES, dtype=[("cost", int)])
    G_d = from_numpy_matrix(A, create_using=nx.DiGraph())
     
    # Transform time matrix into DiGraph
    # Average speed of vehicle is assumed to be 50 km/hr
    # Time unit is in minutes, distance unit is in km    
    TRAVEL_TIMES = [[round(60*float(j)/AVERAGE_SPEED,0) for j in i] for i in DISTANCES]

    A = matrix(TRAVEL_TIMES, dtype=[("time", int)])
    G_t = from_numpy_matrix(A, create_using=DiGraph())

    # Merge
    G = nx.compose(G_d, G_t)

    ###Adding frequencies and making the problem periodic in nature
    ##Setting the frequency for each node
    set_node_attributes(G, values=service_levels, name="frequency")

    # The demands are stored as node attributes
    set_node_attributes(G, values=demands, name="demand")

    # The depot is relabeled as Source and Sink
    G = relabel_nodes(G, {0: "Source", len(DISTANCES)-1: "Sink"})

    #Load capacity is set to the load capacity of each truck. Assuming a 10 hour working day to set duration of routes
    #10 hours is 600 minutes
    prob = VehicleRoutingProblem(G, load_capacity=truck_capacity, duration = 600)

    # Setting the planning horizon to 24 days - 6 days working in each week
    prob.periodic = 24

**Comment by Kuifje02** [comment]
> The error does not happen when I just use the Cost Matrix.

Are you saying that the error occurs when you add travel times ?

**Comment by sumi1234** [comment]
> Are you saying that the error occurs when you add travel times ?
Yes. I am not sure what exactly causes it, since it does not always happen after adding the travel times. For my code - I am deriving the travel times from the distance matrix itself. For some sets of data I get this error, for others I don't.

Environment Details : I am running on Windows 10 using python 3.7.6, NetworkX 2.4 and cspy 0.1.0

**Comment by Kuifje02** [comment]
Hmm the fact that it seems to depend on the data set is weird. If you could provide such a data set so I can reproduce the error, it would be great.

**Comment by torressa** [comment]
Just to rule it out, I seem to remember getting a similar error when experimenting with `time_limit`
Try and increase it just in case.

**Comment by sumi1234** [comment]
> Just to rule it out, I seem to remember getting a similar error when experimenting with time_limit
Try and increase it just in case.

This seems to solve it - I don't get the error on removing the `time_limit `parameter or making it much longer. I am curious - what exactly leads to this error ? Is it because of the way the solution space is being searched during column generation ?

**Comment by Kuifje02** [comment]
Thanks @torressa for saving us some time :) !

What is weird is that the error is raised while calling `self._initialize()`, which is before the search, and before the time limit is actually considered.

What `time_limit` value causes the error ?

**Comment by torressa** [comment]
Haha lucky guess :laughing: 
I think it's just low values, for example 0 was throwing the error when I was initially testing it.
I didn't dig into it unfortunately..

**Comment by sumi1234** [comment]
> I think it's just low values, for example 0 was throwing the error when I was initially testing 

I was getting an error for time_limit of 60, 120. For some datasets where the input data could lead to an infeasible solution - I was getting this error at higher values of 600, 1200 as well ( e.g. frequency of visits for one node was greater than the planning period ).

> What is weird is that the error is raised while calling self._initialize(), which is before the search, and before the time limit is actually considered.

@Kuifje02 Sometimes, restarting my python instance stopped the error from appearing. It might be a python 3 related quirk on how we are accessing the edge list in NetworkX. It is just a guess as I am pretty new to graph algorithms in general

Providing my data below for reference in .pkl format, hope it helps in testing !  
( Code used for running the PVRP is same as the one in my original post )
- List of lists representing the distance matrix -[ https://drive.google.com/file/d/1Fki5JYCVsvROpv7rp5ryB-g_Rq0diH7_/view?usp=sharing]
- Dictionary of Frequency of visits for each node - [https://drive.google.com/file/d/1ZVBz_vGpiCH4J4wYX3-DnD17lHXfTFXM/view?usp=sharing]
- Dictionary of Demands for each node - [https://drive.google.com/file/d/15BkHCO41_q4ud-JBOW0y28dmLxGYDTze/view?usp=sharing]

**Comment by Kuifje02** [comment]
Ok, thanks @sumi1234  for sharing the input data. It turns out the error is raised not because of the time limit. This is due to the fact that when using 
```
A = matrix(DISTANCES, dtype=[("cost", int)])
G_d = from_numpy_matrix(A, create_using=nx.DiGraph())
```
when the coeficient in the A matrix is 0, it does not create the edge. And so there are two nodes (103 and 110) which are not linked to the Source and the Sink. And so it cannot properly run this bit of code:

```
~\Desktop\Supply_Chain_Tool_Streamlined\code_w_balanced_schedules\vrpy\main.py in _convert_initial_routes_to_digraphs(self)
    514             edges = list(zip(r[:-1], r[1:]))
    515             for (i, j) in edges:
--> 516                 edge_cost = self.G.edges[i, j]["cost"][0]
```
as `self.G.edges[Source,103] `does not exist!

Quick fix for @sumi1234 : create the missing edges manually. If the connexion does physically exist and the distance is 0, put a very small cost (0.01, or 1 if you are using integers). If the edge does not exist, put a very high cost. 

As for myself and @torressa, we will handle this in another issue to : 

- create the edge automatically with a high cost, so that the Source and Sink are always reachable.

**Comment by sumi1234** [comment]
Thank you so much !! Really appreciate the quick fix @Kuifje02
