### ISSUE TITLE
General Question : Is it possible to have some of the routes span multiple days in periodic VRP ?

### ISSUE THREAD

**Issue by sumi1234** [Kuifje02/vrpy#40]
Thanks again for developing this library and the prompt responses to all of the issues. It is a great alternative to ORTools for VRP problems and much easier to use !!

Is it possible to have some of the routes span multiple days in periodic VRP ? e.g. I am planning routes over a month and some customers are very far away, requiring a round trip spanning multiple days. Something like below - 
```
Day 1, Route 1 -> Source -> Customer 1
Day 2, Route 1 -> Customer 1 -> Sink ( Back to Depot ) -> Customer 2 -> Sink
```

Any direction or links where you have seen this implemented would also be great. I understand that multiple trips may or may not fit into the existing code-base easily.

**Comment by Kuifje02** [comment]
> Thanks again for developing this library and the prompt responses to all of the issues. It is a great alternative to ORTools for VRP problems and much easier to use !!

Thanks for your kind words. Having feedback like yours is what make such librairies possible ! 

> Is it possible to have some of the routes span multiple days in periodic VRP ? e.g. I am planning routes over a month and some customers are very far away, requiring a round trip spanning multiple days.

There are two features in your request : 

1. **Multiple trips**. Right now, multiple trips are not featured in vrpy. But, it is definitely something to add on the TO DO list, which is bigger and bigger every day! In the mean time, you could solve the problem and then merge compatible routes yourself. Merging may imply to change start times, but I think this would not be too hard. I may need more information to fully understand your problem. May I contact you privately by mail ?


2. **Routes spanning multiple days.** I don't think this is a problem either, but probably I am missing some of the tricky stuff. 

If you have a toy data set, perhaps we could look into this more attentively.

**Comment by sumi1234** [comment]
>Multiple trips. Right now, multiple trips are not featured in vrpy. But, it is definitely something to add on the TO DO list, which is bigger and bigger every day! In the mean time, you could solve the problem and then merge compatible routes yourself. Merging may imply to change start times, but I think this would not be too hard. I may need more information to fully understand your problem. May I contact you privately by mail ?

@Kuifje02 really appreciate the support ! Email would be great. I have a toy data-set that can be used to test both the scenarios.

**Comment by Kuifje02** [comment]
closing for now

**Comment by guifcoelho** [comment]
Hello! I know that this issue is closed but I have a use case very similar to this one. I have routes with very distant delivery points, where the entire round trip could take up to 2 to 3 days.

Do you have plans to include this feature on a new release?

**Comment by Kuifje02** [comment]
Actually, I am not sure why the current version could not handle this. What happens if you try solving it as is ?

**Comment by guifcoelho** [comment]
Sorry, I've just realized I may have missed the topic. I don't have a periodic problem. I have a vrp with time windows. However, my routes as long, and so the time windows must be repeated over different days.

For example:
- If a delivery point is served on the first day of a route, it must be served within windows W1 e W2.
- But, if the same delivery point is served on the 2nd day (on a different scenario run), it must respect windows W1+24 and W2+24.
- This should go on for day 3, 4, etc.., repecting the max duration parameter.

Another option would be to provide multiple time windows as input.

Do you have any idea if I can run something like this with VRPY?

PS: I might have some use cases where I mix the situation above and periodic deliveries, but I want to try the above first.

**Comment by Kuifje02** [comment]
This is indeed a different topic, and I have opened an issue dedicated to multiple time windows. Currently, this is not supported unfortunately.

**Comment by guifcoelho** [comment]
Hello! Thank you for the response. I will keep track of it.
