### ISSUE TITLE
Hyper-heuristic for subproblem algorithm selection

### ISSUE THREAD

**Issue by torressa** [Kuifje02/vrpy#41]
One for future @Halvaros:

There are three different ways of solving the subproblems (LP, Greedy and cspy) and it is not clear beforehand which is one is going to be better/faster. I think it'd be a cool idea to implement a hyper-heuristic to apply different ones adaptively (based on some criteria like solution quality and/or speed). 
I'm not too sure about which one would be the best one, but I have few papers that are good starting points:

- Pretty recent review by [Drake et al. (2019)](https://www.sciencedirect.com/science/article/pii/S0377221719306526#bib0173). We are interested in _selection_ hyper-heuristics.
- I've used the one by [Özcan et al. (2010)](https://mustafamisir.github.io/papers/ozcan10areinforcement.pdf) also in a column generation scenario (code to be public soon) but it's pretty old and a overly simplistic (cool name though).

I propose the following steps

- [x] Comparison of different subproblem performance per benchmark (to justify the hyper-heuristic implementation in the first place)
- [x] Research of hyper-heuristics (shop around for good algorithms, nothing too computationally expensive)
- [x] Implementation (pick one, implement it, and see how it performs)

**Comment by Kuifje02** [comment]
> There are three different ways of solving the subproblems (LP, Greedy and cspy) and it is not clear beforehand which is one is going to be better/faster

Just to add a clarification, as described in this [paper](https://www.sciencedirect.com/science/article/abs/pii/S0377221717306045), greedy is run before LP/cspy to try and catch some extra easy columns. And only if there are no time windows, no distribution+collection, no pickup and delivery. 

Overall, @torressa's idea is very good!

**Comment by Halvaros** [comment]
@torressa and I found that the hyperheuristics runs really fast on many of the the augerat instances. It does not solve the subproblems exactly, but it could possibly be made as a viable separete option where solving exactly is done after this method is exhausted.  

|Instance     |Pricing strategy|Subproblem type|Dived|Greedy|Runtime            |# of iterations|Integrality gap       |Optimality gap    |Optimal                            |
|-------------|----------------|---------------|-----|------|-------------------|---------------|----------------------|------------------|-----------------------------------|
|P-n19-k2.vrp |Hyper           |cspy           |False|True  |0.21318411827087402|1              |Not-valid             |3.30188679245283  |False                              |
|P-n20-k2.vrp |Hyper           |cspy           |False|True  |0.250626802444458  |1              |Not-valid             |2.7777777777777777|False                              |
|P-n19-k2.vrp |Hyper           |cspy           |False|True  |0.20723199844360352|1              |Not-valid             |3.30188679245283  |False                              |
|P-n20-k2.vrp |Hyper           |cspy           |False|True  |0.215440034866333  |1              |Not-valid             |2.7777777777777777|False                              |
|P-n19-k2.vrp |Hyper           |cspy           |False|True  |0.20670270919799805|1              |Not-valid             |3.30188679245283  |False                              |
|P-n20-k2.vrp |Hyper           |cspy           |False|True  |0.21358871459960938|1              |Not-valid             |2.7777777777777777|False                              |
|P-n19-k2.vrp |Hyper           |cspy           |False|True  |0.38613104820251465|1              |Not-valid             |3.30188679245283  |False                              |
|P-n16-k8.vrp |Hyper           |cspy           |False|True  |0.4185924530029297 |1              |Not-valid             |4.444444444444445 |False                              |
|P-n20-k2.vrp |Hyper           |cspy           |False|True  |0.4157373905181885 |1              |Not-valid             |2.7777777777777777|False                              |
|P-n21-k2.vrp |Hyper           |cspy           |False|True  |0.4479820728302002 |1              |Not-valid             |6.161137440758294 |False                              |
|P-n22-k2.vrp |Hyper           |cspy           |False|True  |0.46588873863220215|1              |Not-valid             |7.4074074074074066|False                              |
|P-n16-k8.vrp |Hyper           |cspy           |False|True  |0.2245781421661377 |1              |Not-valid             |4.444444444444445 |False                              |
|P-n19-k2.vrp |Hyper           |cspy           |False|True  |0.23115181922912598|1              |Not-valid             |3.30188679245283  |False                              |
|P-n20-k2.vrp |Hyper           |cspy           |False|True  |0.30705881118774414|1              |Not-valid             |2.7777777777777777|False                              |
|P-n21-k2.vrp |Hyper           |cspy           |False|True  |0.2763192653656006 |1              |Not-valid             |6.161137440758294 |False                              |
|P-n22-k2.vrp |Hyper           |cspy           |False|True  |0.2833895683288574 |1              |Not-valid             |7.4074074074074066|False                              |
|A-n32-k5.vrp |Hyper           |cspy           |False|True  |0.6040635108947754 |1              |Not-valid             |10.714285714285714|False                              |
|A-n32-k5.vrp |Hyper           |cspy           |False|True  |0.7722487449645996 |1              |Not-valid             |10.714285714285714|False                              |
|A-n32-k5.vrp |Hyper           |cspy           |False|True  |0.40858030319213867|1              |Not-valid             |10.714285714285714|False                              |
|A-n80-k10.vrp|Hyper           |cspy           |False|True  |1.8365938663482666 |2              |0.08237299260634846   |4.991491775382871 |False                              |
|A-n46-k7.vrp |Hyper           |cspy           |False|True  |0.7131001949310303 |2              |0.0                   |1.75054704595186  |False                              |
|A-n48-k7.vrp |Hyper           |cspy           |False|True  |0.8751752376556396 |2              |0.3115264797507788    |5.032618825722274 |False                              |
|A-n53-k7.vrp |Hyper           |cspy           |False|True  |1.146594524383545  |2              |0.3248259860788863    |7.029702970297031 |False                              |
|A-n54-k7.vrp |Hyper           |cspy           |False|True  |1.0341613292694092 |2              |0.0                   |1.1996572407883461|False                              |
|A-n55-k9.vrp |Hyper           |cspy           |False|True  |0.9505250453948975 |2              |0.0                   |6.616961789375582 |False                              |
|A-n60-k9.vrp |Hyper           |cspy           |False|True  |1.1048979759216309 |2              |0.0                   |1.7725258493353029|False                              |
|A-n61-k9.vrp |Hyper           |cspy           |False|True  |1.1352455615997314 |1              |Not-valid             |2.9013539651837523|False                              |
|A-n62-k8.vrp |Hyper           |cspy           |False|True  |1.3980894088745117 |2              |0.6369426751592357    |4.270186335403727 |False                              |
|A-n63-k10.vrp|Hyper           |cspy           |False|True  |1.3913743495941162 |2              |0.035855145213338116  |6.164383561643835 |False                              |
|A-n63-k9.vrp |Hyper           |cspy           |False|True  |1.397878885269165  |1              |Not-valid             |2.4752475247524752|False                              |
|A-n64-k9.vrp |Hyper           |cspy           |False|True  |1.7867610454559326 |1              |Not-valid             |7.137758743754461 |False                              |
|A-n65-k9.vrp |Hyper           |cspy           |False|True  |1.3440160751342773 |2              |0.0                   |5.621805792163544 |False                              |
|A-n69-k9.vrp |Hyper           |cspy           |False|True  |1.422455072402954  |2              |0.4061738424045491    |6.643658326143227 |False                              |
|A-n80-k10.vrp|Hyper           |cspy           |False|True  |1.961533784866333  |2              |0.0                   |4.991491775382871 |False                              |
|A-n46-k7.vrp |BestPaths       |cspy           |False|True  |1.5543429851531982 |7              |0.05379236148466917   |1.75054704595186  |False                              |
|A-n48-k7.vrp |BestPaths       |cspy           |False|True  |0.8669619560241699 |2              |0.0                   |5.032618825722274 |False                              |
|A-n69-k9.vrp |BestPaths       |cspy           |False|True  |1.7895958423614502 |2              |0.4061738424045491    |6.643658326143227 |False                              |
|A-n80-k10.vrp|BestPaths       |cspy           |False|True  |2.877331495285034  |3              |0.08237299260634846   |4.991491775382871 |False                              |
|A-n32-k5.vrp |BestPaths       |cspy           |False|True  |0.8014628887176514 |3              |0.8652364584567784    |8.545918367346939 |False                              |
|A-n32-k5.vrp |Hyper           |cspy           |False|True  |1.00374436378479   |2              |2.135231316725979     |9.821428571428571 |False                              |
|A-n33-k5.vrp |Hyper           |cspy           |False|True  |0.4673600196838379 |2              |0.0                   |4.084720121028744 |False                              |
|A-n33-k5.vrp |Hyper           |cspy           |False|True  |0.4796595573425293 |2              |0.0                   |4.084720121028744 |False                              |
|A-n33-k5.vrp |Hyper           |cspy           |False|True  |0.5087614059448242 |2              |0.0                   |4.084720121028744 |False                              |

**Comment by torressa** [comment]
@Halvaros This is so cool!
@Kuifje02 Apart from the hyper-heuristic generated pricing strategy, it can be generalised by trying not to solve the exact version of the subproblems (if any pricing strategy is set) until some criteria is met. See [these lines](https://github.com/Halvaros/vrpy/blob/dc144bb0be05dec12925aad74cdeafd8a5992f1b/vrpy/main.py#L349-L405).
We could, for example at line 399 change 
, only solve the problem exactly if the pricing heuristic has stagnated, maybe use `no_improvement`?
Anyway, see what you think

**Comment by Kuifje02** [comment]
Nice work guys, This is interesting!

@torressa I agree, solving the problem exactly as a last resort is probably the best strategy.

@Halvaros :
1/ In the end which hyperheuristic is implemented ? Is it described in one the papers mentioned above ? (Drake or Ozcan ?)
I would like to understand the concept more thoroughly (or just see the pseudocode).
2/In [hyperheuristic.py](https://github.com/Halvaros/vrpy/blob/dc144bb0be05dec12925aad74cdeafd8a5992f1b/vrpy/hyperheuristic.py), some comments are in Norwegian. As I am not fluent in this language :D it would me good to translate in English for future code maintenance. Tusen takk 👍

**Comment by torressa** [comment]
Just for future comparison, with this set up (averages)

  | VRPy |   | OR-Tools (python) |  
-- | -- | -- | -- | --
Set | CPU time (s) | Opt. Gap | CPU time (s) | Opt. Gap
A | 1.03 | 4.86 | 0.46 | 8.11
B | 1.09 | 6.29 | 0.51 | 5.45
P | 1.02 | 5.80 | 0.47 | 7.31

**Comment by Kuifje02** [comment]
Wow! great performances! I will need to update the performance profiles in the [docs](Variables values) as well as in the joss paper. This is great.

**Comment by Halvaros** [comment]
@Kuifje02 I will make the comments english from now on! Bare hyggelig! :D 

Selection and ranking is taken from here. Aside from the fact that they use objective improvement, and I use runtime. 
Ferreira, A. S., Gonçalves, R. A., & Pozo, A. (2017, June). A multi-armed bandit selection strategy for hyper-heuristics. In 2017 IEEE Congress on Evolutionary Computation (CEC) (pp. 525-532). IEEE.​

Acceptance mechanism is taken from here 
Sabar, N. R., Zhang, X. J., & Song, A. (2015, May). A math-hyper-heuristic approach for large-scale vehicle routing problems with time windows. In 2015 IEEE Congress on Evolutionary Computation (CEC) (pp. 830-837). IEEE.​

Adaptive parameter setting is from here. 
Drake, J. H., Özcan, E., & Burke, E. K. (2012, September). An improved choice function heuristic selection for cross domain heuristic search. In International Conference on Parallel Problem Solving from Nature (pp. 307-316). Springer, Berlin, Heidelberg.
