### ISSUE TITLE
JOSS Review: API

### ISSUE THREAD

**Issue by torressa** [Kuifje02/vrpy#43]
Originally from: https://github.com/openjournals/joss-reviews/issues/2408#issuecomment-651542971 

## API 
- [x] For _Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?_ above, the [API](https://vrpy.readthedocs.io/en/latest/api.html) feels a bit light to me.  Can you add to it?

- [x] Is vrpy.VehicleRoutingProblem the only "public" interface? I believe so, but if not, please add others to API.html. Btw, maybe add all other classes the prefix "_" to hint the private nature?

Who? All

**Comment by Kuifje02** [comment]
@torressa What do you think about this one ?

> * Is vrpy.VehicleRoutingProblem the only "public" interface? I believe so, but if not, please add others to API.html. Btw, maybe add all other classes the prefix "_" to hint the private nature?

VehicleRoutingProblem is our only public class. Is it worth redefining all other classes with a prefix (do you know if this is a standard norm) ? 

And do you think the API should be more documented ? I'm afraid it might be redundant with all the examples.

**Comment by torressa** [comment]
The private class thing is a fair point as I think it's pretty standard: see [here](https://docs.python.org/3/tutorial/classes.html#private-variables).

I'm with you on the API (which rtd doesn't seem to like now) so maybe adding a link to the examples page would make the reviewers happy

**Comment by Kuifje02** [comment]
Sounds good, I'm on it.
