### ISSUE TITLE
JOSS Review: Paper edits

### ISSUE THREAD

**Issue by torressa** [Kuifje02/vrpy#44]
Originally from: https://github.com/openjournals/joss-reviews/issues/2408#issuecomment-651542971 and https://github.com/openjournals/joss-reviews/issues/2408#issuecomment-655272567

## Paper edits
- [x] On page 1 one of the paper, change "thus benefits of" to "thus benefits from"
- [x] I suggest changing the name of the paper to be slightly more specific - "...for solving a range of vehicle routing problems using the column generation approach" - since this seems to be the major contribution?
- [x] For _Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support_, there doesn't seem to be much in the docs related to this.  Can you improve it?
- [x] For _State of the field: Do the authors describe how this software compares to other commonly-used packages?_, can you add some discussion of other relevant packages?  For example, you mention networkx, cspy, Clp, but not other libraries such as ortools or py-ga-VRPTW.

 - [x] Is there any reports/performance you can refer to? If full-blown comparison results are not available, even a quick comment might help the user on what to expect from this library? Is this designed to be competitive in terms of runtime and solution quality? OR, there is no such performance claim but instead, it offers an easy-to-use, unified API for many variants of VRP?

- [x] Please mention in the paper that the library does NOT solve the instances to optimality. See my comment on the performance above.

- [x] You have a nice quick start example in the docs. Maybe add that to the paper?

- [x] "The flexibility and genericity of vrpy is strongly due to ... the relevance of cspy.". I am not sure what you mean here, please consider a rephrase

- [x] The high-level intro to the ColGen approach is nice. For the interested reader who might want to see how different variants of VRP can be formulation in this ColGen framework is there a paper or technical report that you can cite/refer? It is not obvious how all of the variants are modeled, the trick happens in the pricing and a reference of details of each formulation would be nice to have.

- [x] Could you please add a word about other libraries and compare/contrast with this one? Does it solve more variants, why should the reader/user consider this library? For example, you mention examples from the ORTools, a comment on the comparison with ORTools and other libraries would be good for the reader to evaluate.

- [x] Any performance to report and/or refer to? There are many standard VRP benchmarks for this purpose, and I see that you already use Solomon etc.

- [ ] Add some comments on your strategy for testing the library? In particular; testing invalid conditions and testing behavior (optimal value and route)

Who? @torressa @Kuifje02

**Comment by bstabler** [comment]
@torressa - note that the community guidelines don't need to go in the paper but could be in a README, a CONTRIBUTING file, or the docs.

**Comment by Kuifje02** [comment]
> * For _State of the field: Do the authors describe how this software compares to other commonly-used packages?_, can you add some discussion of other relevant packages?  For example, you mention networkx, cspy, Clp, but not other libraries such as ortools or py-ga-VRPTW.

Comparisons with ortools are in process. Comparing with py-ga-VRPTW is a great idea! We can run the Solomon instances and compare the three.

**Comment by Kuifje02** [comment]
> * Add some comments on your strategy for testing the library? In particular; testing invalid conditions and testing behavior (optimal value and route)

Not sure I understand this one

**Comment by Kuifje02** [comment]
Most suggestions from https://github.com/openjournals/joss-reviews/issues/2408#issuecomment-655272567 have been taken into account, just need @torressa to validate modifications. 

Also, I hope the paper is not too long now.

**Comment by Kuifje02** [comment]
@torressa what do you think of this version of the paper ? 
- Maybe a word on the hyperheuristic ?
- Maybe performances on Augerat data sets have improved ?

**Comment by torressa** [comment]
It's looking really good! I've just updated the results in `performance_profiles` with some new ones.
Also changed the notebook and csv files so they can be rendered on github (except for the res column in the vrpy file because I didn't have that)

@Halvaros maybe you can write something about the hyper-heuristic in the paper too? 
I guess you'll be co-author as well :)

**Comment by Halvaros** [comment]
@torressa Sure, I can do that!

**Comment by Kuifje02** [comment]
I think the revised paper is satisfactory, although maybe too long for JOSS requirements. I am closing for now.
