### ISSUE TITLE
Citing the library

### ISSUE THREAD

**Issue by egh312** [Kuifje02/vrpy#45]
Hi 
Hopefully a quick one, looking to cite the library in my masters thesis, is their a particular paper/citation you have preference for?
Thanks for your hard work!
Best.
Ed

**Comment by torressa** [comment]
Hey @egh312 
Thanks for asking! Unless @Kuifje02 disagrees, something like this works

```
@misc{
  author = {Montagné, Romain and {Torres Sanchez}, David},
  title = {{A python framework for solving the VRP and its variants with column generation.}},
  year = {2020},
  url = {https://github.com/Kuifje02/vrpy}
}
```
