### ISSUE TITLE
sphinx formats docstring Attr on same line

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#5]
Sphinx formats docstring Attributes on same line :
![image](https://user-images.githubusercontent.com/19840033/78378346-1d651580-75d1-11ea-89dc-3764241864ab.png)

I noticed that if I skip a line between attributes, its fine, but I assume this is not normal.

The issue was reported [here](https://stackoverflow.com/questions/49564783/why-does-sphinx-format-my-docstring-parameters-on-the-same-line) but the solution (add blank line between description and Args does not work)

**Comment by torressa** [comment]
Needs a sphinx plugin
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
