### ISSUE TITLE
Problem when running "python3 -m pytest benchmarks/" 

### ISSUE THREAD

**Issue by AliArishi** [Kuifje02/vrpy#69]
The tests failed when I ran the code FOR test_cvrp_augerat.py.... the testing output :

platform win32 -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1

benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False w
armup_iterations=100000)

plugins: hypothesis-5.5.4, arraydiff-0.3, astropy-header-0.1.2, benchmark-3.2.3, doctestplus-0.5.0, openfiles-0.4.0, remotedata-0.3.2
collected 9 items                                                                                                                                      

benchmarkss\tests\test_cvrp_augerat.py FFFF

**Comment by Kuifje02** [comment]
I am unable to replicate your error. 

Can you run the following from the root directory ?

`python -m pytest benchmarks/`

**Comment by Kuifje02** [comment]
closing for now

**Comment by AliArishi** [comment]
No problem.

Thank you for your response and help.

Best

Ali
