### ISSUE TITLE
Revisit nodes in the Pickup and Delivery Problem

### ISSUE THREAD

**Issue by 1kastner** [Kuifje02/vrpy#76]
First of all thank you very much for sharing this great project! The documentation and code have been very helpful for me!

Now I wanted to tamper around a bit with one example and step-by-step reshape it to fit my own requirements. One important requirement is that a vehicle has a capacity of 1. At the nodes, the goods that need to be transported will be greater than 1. That means that one vehicle needs to revisit one node several times. Possibly the vehicle will even move back and forth between the same two nodes A and B until all goods are transported from A to B.

Therefore, I picked your example code and just adjusted the capacity:

```
from networkx import from_numpy_matrix, relabel_nodes, DiGraph
from numpy import array

from examples.data import DISTANCES, PICKUPS_DELIVERIES

from vrpy import VehicleRoutingProblem

# Transform distance matrix to DiGraph
A = array(DISTANCES, dtype=[("cost", int)])
G = from_numpy_matrix(A, create_using=DiGraph())

# Set demands and requests
for (u, v) in PICKUPS_DELIVERIES:
    G.nodes[u]["request"] = v
    G.nodes[u]["demand"] = PICKUPS_DELIVERIES[(u, v)]
    G.nodes[v]["demand"] = -PICKUPS_DELIVERIES[(u, v)]

# Relabel depot
G = relabel_nodes(G, {0: "Source", 17: "Sink"})

if __name__ == "__main__":

    prob = VehicleRoutingProblem(G,
                                 load_capacity=1,
                                 pickup_delivery=True)
    prob.solve(cspy=False)
    print(prob.best_value)
    print(prob.best_routes)
    print(prob.node_load)
```

This resulted in the following error message:
`ValueError: Demand 2 at node 2 larger than max capacity 1.`

Is there a way how this error can be avoided? Or is the library just not suitable for the kind of problem I described above?

Thank you very much for your great work and your ideas on this topic!

**Comment by Kuifje02** [comment]
Thanks for your feedback !

You can try and duplicate your nodes as many times as required. For example, if you have a demand that equals $2$, you need two nodes, each with a $1$ unit demand. Since the truck has capacity $1$, the solution will have $2$ trips to the initial node (one for each unit of each duplicated node).

**Comment by 1kastner** [comment]
Thank you very much for the suggestion, it is very suitable!
