### ISSUE TITLE
Having a node at which both a pickup and a delivery is performed

### ISSUE THREAD

**Issue by 1kastner** [Kuifje02/vrpy#77]
First of all thank you very much for sharing this great project! The documentation and code have been very helpful for me!

While tampering around with the example, I thought about how to implement a two transportation jobs: One from A to B and a second one from B to A. Is that currently feasible? For illustration, here is the code with some naive adjustments to highlight my idea:

```
#!/usr/bin/env python
# coding: utf-8

from networkx import from_numpy_matrix, relabel_nodes, DiGraph
from numpy import array

from examples.data import DISTANCES

from vrpy import VehicleRoutingProblem

# Transform distance matrix to DiGraph
A = array(DISTANCES, dtype=[("cost", int)])
G = from_numpy_matrix(A, create_using=DiGraph())

PICKUPS_DELIVERIES = {
    (1, 6): 4,
    (6, 1): 4,
}

# Set demands and requests
for (u, v) in PICKUPS_DELIVERIES:
    G.nodes[u]["request"] = v
    G.nodes[u]["demand"] = PICKUPS_DELIVERIES[(u, v)]
    G.nodes[v]["demand"] = -PICKUPS_DELIVERIES[(u, v)]

# Relabel depot
G = relabel_nodes(G, {0: "Source", 17: "Sink"})

prob = VehicleRoutingProblem(G,
                             load_capacity=5,
                             pickup_delivery=True)
prob.solve(cspy=False)
print(prob.best_value)
print(prob.best_routes)
print(prob.node_load)
```

This results in a `Exception: problem Infeasible` and because the demand is modeled as either a positive or a negative number, it is obvious that my code could never work. In this example, a node cannot be the place of both a pickup and a delivery.

Is there a way how my idea can be modeled alternatively in this library? Or is the library just not suitable for the kind of problem I described above?

Thank you very much for your great work and your ideas on this topic!

**Comment by Kuifje02** [comment]
Again, I think you could manage by duplicating the nodes. Create nodes A1, A2, B1, B2 (A1 and B1 as pickup nodes, and A2, B2 as  demand nodes). This way your jobs from A to B and B to A become jobs from A1 to B2 and B1 to A2, respectively.

**Comment by 1kastner** [comment]
Thank you very much for your modeling suggestions.
