### ISSUE TITLE
CVRP with Time Windows (CVRPTW) in docmentation are not working

### ISSUE THREAD

**Issue by rioaurachman** [Kuifje02/vrpy#78]
CVRP with Time Windows (CVRPTW) in docs are not working
docs = https://vrpy.readthedocs.io/en/dev/vrp_variants.html

I did it at https://colab.research.google.com/drive/1kbU-7CNPzQ8hV6kFqzH7fm7TZHyUutTt?usp=sharing

and it show error like this
/usr/local/lib/python3.7/dist-packages/networkx/classes/reportviews.py in __getitem__(self, e)
   1014     def __getitem__(self, e):
   1015         u, v = e
-> 1016         return self._adjdict[u][v]
   1017 
   1018     # EdgeDataView methods

KeyError: 'Sink'

**Comment by Kuifje02** [comment]
Thanks for your feedback.

This is weird. This example only shows the correct syntax but maybe it should be updated.

For an example that works, please refer to [here](https://github.com/Kuifje02/vrpy/tree/master/examples) for the moment.

**Comment by rioaurachman** [comment]
Thank you very much
