### ISSUE TITLE
Testing: Benchmark Instances

### ISSUE THREAD

**Issue by torressa** [Kuifje02/vrpy#8]
That's cool ! I also tested the Solomon case with the 50 first vertices and with the LP version of the sub problem and was able to find the solution of the benchmarks. This is reassuring !The solution is plotted below :

![image](https://user-images.githubusercontent.com/19840033/78832578-cbb2f580-79eb-11ea-8b8e-00769d34170e.png)

For the speed we will probably have to do some profiling to identify the bottlenecks, and maybe some acceleration tricks should be implemented, like the one you mentioned. We will see. Another interesting figure is the rate of convergence of the procedure : 

![image](https://user-images.githubusercontent.com/19840033/78832873-47ad3d80-79ec-11ea-8aab-2de40baf07d2.png)

Most of the time is spent trying to prove optimality. And actually it fails, as I set a 1000 iteration limit. 

But in all cases this is promising and interesting ! Eager to do some comparisons with or-tools !

_Originally posted by @Kuifje02 in https://github.com/torressa/cspy/issues/33#issuecomment-611191335_

**Comment by torressa** [comment]
What's the number of stops for this case? 10?

**Comment by torressa** [comment]
Also, don't think it's a problem as the costs are correct, but the LP prints out some weird paths:

```none
INFO     master_solve_pulp:master_solve_pulp.py:38 ['Source', 17, 15, 'Sink', 18, 19] cost 82.35716436533332
INFO     master_solve_pulp:master_solve_pulp.py:38 ['Source', 9, 11, 14, 13, 'Sink'] cost 84.68340063199719
INFO     master_solve_pulp:master_solve_pulp.py:38 ['Source', 1, 2, 4, 3, 'Sink'] cost 42.41160846433049
INFO     master_solve_pulp:master_solve_pulp.py:38 ['Source', 7, 10, 22, 21, 'Sink'] cost 48.850514869684105
INFO     master_solve_pulp:master_solve_pulp.py:38 ['Source', 23, 20, 'Sink', 24] cost 33.8309518948453
```

**Comment by Kuifje02** [comment]
There is no maximum number of stops. 

Yes, what is printed is G.nodes(), and not the path itself. I've changed this but need to commit, will do it asap.

**Comment by Kuifje02** [comment]
Also, of course the master problem is quite slow with the default sovler (CBC). Do you have access to a commercial solver ?

**Comment by torressa** [comment]
I do have gurobi but I'd rather keep it open source.
cspy is really slow too. Looking at some profiling and graph preprocessing stuff.

**Comment by torressa** [comment]
Do you know anything about this?

![preprocessing](https://user-images.githubusercontent.com/23246013/78896903-9a7d0880-7a71-11ea-964f-43682cc80c01.png)

"p-nearest-neighbor network". 
Seems pretty simple but among all the machine learning stuff it's hard to find the right one.

**Comment by Kuifje02** [comment]
me too I am pro open source. I was just saying that for the tests.

Interesting ! I have never heard about this stuff but I some of these authors were actually my professors in Montreal ! I'll look into it. 

There is also [this](https://pubsonline.informs.org/doi/10.1287/trsc.2018.0878) article/survey that has good stuff. I you can't access it I can send you a copy.

**Comment by torressa** [comment]
That paper is ace! Got everything there

**Comment by Kuifje02** [comment]
Hehe ! it is indeed ! its fresh from last year. Section 3.1.6 got me thinking : it mentions how heuristic versions of the ESPPRC can be solved. Since cspy is designed with a set of heuristics, maybe we could tweak them so that they work even with negative cycles.

**Comment by torressa** [comment]
That would be really cool. I think we should still implement some of the preprocessing techniques discussed in the paper. When they are done and if we enforce time-windows and time constraints, bidirectional will be pretty fast.
I'll look into tweaking some of the heuristics to work with negative cycles. They're all networkx implementations, and I'm not sure what algorithms allow them so will need to do a bit of research first.

**Comment by Kuifje02** [comment]
I was not able to find the same results with lp and cspy : 

![image](https://user-images.githubusercontent.com/19840033/79003950-0172ee00-7b54-11ea-82eb-4077d89460bc.png)

And for some reason with 2-5 nodes, I get a  `networkx.exception.NodeNotFound: Either source Source or target Sink is not in G
` exception, although the Source and Sink are in G.nodes().

**Comment by Kuifje02** [comment]
**With time windows** execution is much faster ! Here is what I get : 

![image](https://user-images.githubusercontent.com/19840033/79016549-9e8f5000-7b6f-11ea-83d9-1b67d788f317.png)

For n > 11, I think there is a problem.

**Comment by torressa** [comment]
Cool! Thanks for adding to code to produce the tables.
Will have a look into it.
I've been trying to figure out how to relax the negative cycle assumption for the algorithms. Nearly there I think

**Comment by Kuifje02** [comment]
I added a CVRP example from [Augerat et al.](http://vrp.galgos.inf.puc-rio.br/index.php/en/)). 
Interesting as the column generation procedure fails to find the optimal value (known from the benchmarks). The difference is due to the fact that we don't branch and solve as a MIP once all negative columns have been generated.

**Comment by Kuifje02** [comment]
Also added a multi depot instance from [Cordeau et al.](http://neo.lcc.uma.es/vrp/vrp-instances/multiple-depot-vrp-instances/).
Needs more genericity but enough to get started.

**Comment by torressa** [comment]
Cool stuff! 
Just checked the Solomon again. Latest commit fixes https://github.com/Kuifje02/vrpy/issues/8#issuecomment-612093360.
The ones that errored still do, haven't looked into them yet, but everything else works! Both time-windows and w/o time-windows. Funnilly enough, w/o time windows is now faster than the lp haha

Also, I think the subproblem_lp needs the service time in the time-windows constraint.

**Comment by torressa** [comment]
cspy works for Augerat. Allot slower using the heuristic.

**Comment by torressa** [comment]
Ok, cspy wasn't working for n=25, not sure about others yet.
The reason was that the resource that was supposed to contain the time was 0 throughout.
So it was working for the cases where I guess time-windows didn't matter.
Anyways, it works, but it's slow as hell, I think the upper bounds on the duration and demands are terrible. Going to see if I can find some better ones.

**Comment by torressa** [comment]
Yeh, realised how stupid that was.. I'm not sure what's going on with the time windows to be honest.
It even works without the custom REF..

**Comment by Kuifje02** [comment]
I added another cvrp example [from ortools](https://developers.google.com/optimization/routing/cvrp).

What I found out is quite funny. When I run vrpy with no initial solution, it finds a better solution than ortools ! So ortools is not optimal on this specific instance. 
Then I tried setting ortools best solution as an initial solution and the problem degenerates and is unable to find a better solution ! That is very strange.

**Comment by Kuifje02** [comment]
I add a pickup and delivery option also [from ortools](https://developers.google.com/optimization/routing/pickup_delivery). 

- It is not the same version as in Righini and Salani's article (I will try to reproduce their version as well)

- Only the LP version can handle it for the moment. With cspy, I am not sure how to model (yet) the fact that a path must contain at least one pickup and delivery pair of nodes.

**Comment by torressa** [comment]
Nice! I'll look into it when I'm done with the REF issue.
I think it might be done, just running the solomon tests to be sure.

**Comment by Kuifje02** [comment]
With the [ortools vrptw example](https://developers.google.com/optimization/routing/vrptw), I am able to find the same routes as them. The solution cost is a little different, because they compute the time matrix in a weird way that I cannot reproduce. Doesn't really matter for now.

**Comment by Kuifje02** [comment]
I will added an example of the distribution and collection problem described by Righini and Salani. I have only implemented the lp version, but the cspy version is ont its way !
And by the way, their [article](https://pubsonline.informs.org/doi/10.1287/trsc.1050.0118) is an absolute gold mine with many tricks we can implement to boost the code !
