### ISSUE TITLE
Periodic VRP not working with num_vehicles option

### ISSUE THREAD

**Issue by mhdsyarif** [Kuifje02/vrpy#82]
Dear, thanks before for VRPY

I added the `periodic parameter` in the documentation https://vrpy.readthedocs.io/en/latest/examples.html#limited-fleet-and-dropping-visits

prob = VehicleRoutingProblem(G, load_capacity=15, num_vehicles=4, `periodic=5`, drop_penalty=1000)

and it show error like this:
<img width="974" alt="image" src="https://user-images.githubusercontent.com/5978109/114686770-491aef80-9d3d-11eb-8a09-a4bf40d0e6eb.png">

**Comment by Kuifje02** [comment]
Hello,

It is not easy to see what is going on only with the above picture. But can you try solving without the "num_vehicles=4" ?

**Comment by mhdsyarif** [comment]
Hello @Kuifje02 

If I remove num_vehicles, periodic can work fine but there is a trade off of not being able to determine the number of vehicles

**Comment by Kuifje02** [comment]
Ok, thanks for pointing this out. I will have to look into it. 

How many vehicles do you get without imposing num_vehicles = 4 ?

**Comment by mhdsyarif** [comment]
Hello @Kuifje02 ,

Vehicle results = 5

prob.best_routes
`{1: ['Source', 8, 'Sink'], 2: ['Source', 9, 10, 2, 6, 5, 'Sink'], 3: ['Source', 14, 16, 9, 'Sink'], 4: ['Source', 12, 11, 4, 3, 1, 'Sink'], 5: ['Source', 13, 7, 'Sink']}`
prob.schedule
`{2: [1], 0: [2], 4: [3], 3: [4], 1: [5]}`

**Comment by Kuifje02** [comment]
The reason why the `num_vehicles` option is not possible for the periodic version is because `num_vehicles` is the maximum number of vehicles available on a given day, and not over the total time span. 

It may be a good idea to allow `num_vehicles` when computing the schedule (prob.schedule).

**Comment by Kuifje02** [comment]
@mhdsyarif you can now have both options as input (`periodic` and `num_vehicles`). But don't forget, `num_vehicles` is the number of vehicles available EACH DAY, and not overt the time span.
