### ISSUE TITLE
VRP with time windows issue

### ISSUE THREAD

**Issue by rcse2006** [Kuifje02/vrpy#83]
Hello, Thanks vrpy python package,

I am trying to implement VRP with time windows and i am getting below error. Please provide your valuable input. 
Code: 

from networkx import DiGraph, from_numpy_matrix, relabel_nodes, set_node_attributes, compose
import networkx as nx
from numpy import array
from vrpy import VehicleRoutingProblem

DISTANCES = [
 [0, 0, 2259, 2068, 7182, 8154, 8170],
 [0, 2259, 0, 399, 5855, 6795, 6806],
 [0, 2068, 399, 0, 5684, 6639, 6652],
 [0, 7182, 5855, 5684, 0, 973,  989],
 [0, 8154, 6795, 6639, 973, 0, 20],
 [0, 8170, 6806, 6652, 989, 20, 0],
 [0, 0, 0, 0, 0, 0, 0]]

TRAVEL_TIMES = [
 [0, 4, 3, 14, 16, 16, 0],
 [0, 0, 1, 7, 12, 13, 4],
 [0, 1, 0, 9, 12, 12, 3],
 [0, 12, 11, 0, 2, 2, 14],
 [0, 12, 13, 2, 0, 1, 16],
 [0, 13, 12, 2, 1, 0, 16],
 [0, 0, 0, 0, 0, 0, 0]]

# Time windows (key: node, value: lower/upper bound)
TIME_WINDOWS_LOWER = {0: 0, 1: 3, 2: 3, 3: 11, 4: 12, 5: 13, 6: 14}
TIME_WINDOWS_UPPER = {1: 5, 2:4 , 3: 12, 4: 13, 5: 19, 6: 20}

# Transform distance matrix into DiGraph
A = array(DISTANCES, dtype=[("cost", int)])
G_d = from_numpy_matrix(A, create_using=DiGraph())

# Transform time matrix into DiGraph
A = array(TRAVEL_TIMES, dtype=[("time", int)])
G_t = from_numpy_matrix(A, create_using=DiGraph())

# Merge
G = compose(G_d, G_t)

# Set time windows
set_node_attributes(G, values=TIME_WINDOWS_LOWER, name="lower")
set_node_attributes(G, values=TIME_WINDOWS_UPPER, name="upper")

G = relabel_nodes(G, {0: "Source", 6: "Sink"})
# The VRP is defined and solved
prob = VehicleRoutingProblem(G, time_windows=True)
prob.solve()

Error:
![image](https://user-images.githubusercontent.com/16430713/114715013-b3cf2980-9d43-11eb-81ae-1d5580fd9b94.png)

**Comment by rcse2006** [comment]
Issue if fixed...

**Comment by Kuifje02** [comment]
Great. Would you like to share what was the fix ? Thanks!

**Comment by rcse2006** [comment]
TIME_WINDOWS_UPPER  should not less then TRAVEL_TIMES matrix element.
Changed the TIME_WINDOWS_UPPER = {1: 12, 2: 15, 3: 18, 4: 17, 5: 19} and its working now. Thanks!!!
