### ISSUE TITLE
Mathematical Model of saving algorithm in this program

### ISSUE THREAD

**Issue by Ilham-Akbar** [Kuifje02/vrpy#85]
Can i see or get your mathematical model for this program with the saving algorithm? Cause i need to improve my skill to leraning about it. Please

**Comment by Kuifje02** [comment]
The basic model is [here](https://vrpy.readthedocs.io/en/latest/mathematical_background.html). For more details your can read [the article published in JOSS](https://joss.theoj.org/papers/10.21105/joss.02408), where you can find many references.

You can google Clarke & Wright savings algorithm to find many explanations, for example [here](https://web.mit.edu/urban_or_book/www/book/chapter6/6.4.12.html).
