### ISSUE TITLE
Add parameter to return heuristic solution only

### ISSUE THREAD

**Issue by tcokyasar44** [Kuifje02/vrpy#89]
Title may not be expressing the issue exactly. Here is what I mean. Say, I am only interested in a greedy solution and want the algorithm terminate once the greedy solution is found. I input the following options:

`prob.solve(greedy=True, cspy=False, exact= False, time_limit=60)`

The output is as follows:

```
INFO:vrpy.vrp:new upper bound : max num stops = 44
INFO:vrpy.vrp:Clarke & Wright solution found with value 14418.517991046587 and 2 vehicles
INFO:vrpy.vrp:Greedy solution found with value 8882.48537930919 and 1 vehicles
INFO:vrpy.vrp:iteration 0, 8882.4
INFO:vrpy.vrp:time up !
INFO:vrpy.master_solve_pulp:total cost = 8882.48537930919
```

With the input arguments, shouldn't it stop running right after "Greedy solution found with value...?" What is the iteration 0 for, and what does it try to solve until the time_limit is reached?

Now, also say, I am interested in a heuristic solution that the [Pricing Strategy](https://vrpy.readthedocs.io/en/dev/solving_options.html#pricing-strategy) explains in 1. I run:

`prob.solve(exact= False)`

and receive:

```
INFO:vrpy.vrp:new upper bound : max num stops = 44
INFO:vrpy.vrp:Clarke & Wright solution found with value 14418.517991046587 and 2 vehicles
INFO:vrpy.vrp:Greedy solution found with value 8882.48537930919 and 1 vehicles
INFO:vrpy.vrp:iteration 0, 8882.4
INFO:vrpy.vrp:iteration 1, 8882.4
INFO:vrpy.vrp:iteration 2, 8882.4
INFO:vrpy.vrp:iteration 3, 8882.4
...
```
Does running the iterations mean, no heuristic solution found or would we receive an INFO if it was the case?

**Comment by Kuifje02** [comment]
Setting the `greedy=True` activates a heuristic that is called while solving the pricing problem at each iteration (see the docs [here](https://vrpy.readthedocs.io/en/latest/solving_options.html)). It is NOT refering to the initial solution that is computed with a greedy algorithm. This is always done. 

Iteration 0 is a combination of the Clarke and Wright algorithm, and the Greedy algorithm computed  before hand. Basically, it merges both solutions to get a better one, if possible. In the following iterations, new routes are computed based on a pricing problem and are added to the pool routes. 

When using `exact=False` the subproblem is solved heuristically with one of cspy's heuristics. This does not guarantee a better solution nor a faster computation time. These are just options with which one can play around to see how things go.

**Comment by tcokyasar44** [comment]
Is it fair to say, one chasing only a feasible solution should use Time_Limit = a low value? If yes, is there any min time that should be fed to make sure receiving a feasible solution?

**Comment by torressa** [comment]
That would work, or also setting `max_iter=1` or `0` (just 1 iteration of the column generation algorithm or just return that initial heuristic solution)

**Comment by tcokyasar44** [comment]
I guess, I closed this too quickly because I get the following output when I set time_limit=60. Also tried max_iter = 0 independent from time limit and waited tooooo long, and had to halt.

```
INFO:vrpy.vrp:new upper bound : max num stops = 42
INFO:vrpy.vrp:Clarke & Wright solution found with value 47331.54133974445 and 37 vehicles
INFO:vrpy.vrp:Greedy solution found with value 38583.27650736972 and 16 vehicles
INFO:vrpy.vrp:iteration 0, -72941
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-16-5dbde22a9e4f> in <module>
     38     G.nodes[j]["service_time"] = 100
     39 prob = VehicleRoutingProblem(G, load_capacity=120, duration = 36000)
---> 40 prob.solve(time_limit=60)

~/anaconda3/lib/python3.7/site-packages/vrpy/vrp.py in solve(self, initial_routes, preassignments, pricing_strategy, cspy, exact, time_limit, solver, dive, greedy, max_iter, run_exact)
    236         self._initialize(solver)
    237         self._solve(dive, solver)
--> 238 
    239     @property
    240     def best_routes_type(self):

~/anaconda3/lib/python3.7/site-packages/vrpy/vrp.py in _solve(self, dive, solver)
    452             check_initial_routes(initial_routes=self._initial_routes, G=self.G)
    453         else:
--> 454             # Initial solution is computed with Clarke & Wright (or round trips)
    455             self._get_initial_solution()
    456         # Initial routes are converted to digraphs

~/anaconda3/lib/python3.7/site-packages/vrpy/vrp.py in _column_generation(self)
    474             self._more_routes = True
    475             self._column_generation()
--> 476             (
    477                 self._best_value,
    478                 self._best_routes_as_graphs,

~/anaconda3/lib/python3.7/site-packages/vrpy/vrp.py in _find_columns(self)
    519                 relax=True, time_limit=self._get_time_remaining()
    520             )
--> 521         logger.info("iteration %s, %.6s" % (self._iteration, relaxed_cost))
    522         pricing_strategy = self._get_next_pricing_strategy(relaxed_cost)
    523 

~/anaconda3/lib/python3.7/site-packages/vrpy/vrp.py in _solve_subproblem_with_heuristic(self, pricing_strategy, vehicle, duals, route)
    583         route=None,
    584     ):
--> 585         """Solves pricing problem with input heuristic"""
    586         more_columns = False
    587         if self._pricing_strategy == "Hyper":

~/anaconda3/lib/python3.7/site-packages/vrpy/vrp.py in _attempt_solve_best_edges1(self, vehicle, duals, route)
    624     def _attempt_solve_best_paths(self, vehicle=None, duals=None, route=None):
    625         more_columns = False
--> 626         for k_shortest_paths in [3, 5, 7, 9]:
    627             subproblem = self._def_subproblem(
    628                 duals,

~/anaconda3/lib/python3.7/site-packages/vrpy/subproblem_cspy.py in solve(self, time_limit)
    106         # time-window feasibility
    107         if not self._time_windows or (new_res[2] <= b_j):
--> 108             # and new_res[2] < self._T - a_i - theta_i and
    109             #         a_s <= new_res[2] + theta_s + travel_time_si <= b_s):
    110             # if not self._time_windows or (

~/anaconda3/lib/python3.7/site-packages/cspy/algorithms/bidirectional.py in total_cost(self)
    161         return _path
    162 
--> 163     @property
    164     def total_cost(self):
    165         """Get accumulated cost along the path.

Exception: Please call the .run() method first
```

**Comment by Kuifje02** [comment]
So its seems you have more than 1 000 nodes...that's a lot ! What is happening (I think) is that even 1 iteration is taking too long. Behind the curtains, AFTER each iteration, if the time limit is reached, the loop is ended. 

We could add a parameter to never enter the iteration loop and just keep the solutions from the heuristics (before iteration 0).

**Comment by tcokyasar44** [comment]
That is exactly what I was thinking. That is why I questioned if there would be a lower bound for the time limit to have at least a feasible solution. In some cases, I provide the time limit to the whole program (including preprocessing and the solver), and only to the solver in others. I was trying to understand if that time limit includes the time allocated to Clarke & Wright and the greedy. I think, that resolution could be really nice.

**Comment by Kuifje02** [comment]
Needs some dev with [VeRyPy](https://github.com/yorak/VeRyPy) to have better heuristic solutions.

**Comment by Kuifje02** [comment]
See the [docs](https://vrpy.readthedocs.io/en/dev/solving_options.html) for an example.
