### ISSUE TITLE
Can we prioritize the collection locations and then distribution locations in simultaneous collection and distribution?

### ISSUE THREAD

**Issue by prince4249** [Kuifje02/vrpy#95]
I have 3 types of nodes.
1) Collection point ('C)  
2) Distribution point ('D)
3) Both Collection and Distribution ('CD')

In any one of the routes, I wish to first visit all 'D's location then 'CD's and at the last 'C's . Is there any way to implement this ?

**Comment by Kuifje02** [comment]
You may be able to achieve this by carefully defining your graph, and the costs. For example, if you do not create any edges from the Source to the D or CD points, the first point will necessarily be a C point. Similarly, do not create any edges from C points to the Sink, and no edges from C points to CD points. And on the edges from D to C, etc ...
