### ISSUE TITLE
Clarke & Wright solution

### ISSUE THREAD

**Issue by piaulous** [Kuifje02/vrpy#98]
Is there an option to get the routing solution from Clark and Wright?

**Comment by Kuifje02** [comment]
With the current API, this is not possible. It will be in the next release.

In the mean time, you can copy paste and use [the code](https://github.com/Kuifje02/vrpy/blob/master/vrpy/clarke_wright.py) that is used behind the curtains.

**Comment by Kuifje02** [comment]
See the [docs](https://vrpy.readthedocs.io/en/dev/solving_options.html) for an example.
